/// <reference types="react" />
interface MultiEntryAccordionItemProps {
    $hasSubtitle: boolean;
}
export declare const SubtitleText: import("styled-components/dist/types").IStyledComponentBase<"web", import("styled-components").FastOmit<import("styled-components").FastOmit<import("styled-components/dist/types").Substitute<import("styled-components/dist/types").Substitute<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, Omit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "ref"> & {
    ref?: import("react").RefObject<HTMLParagraphElement> | ((instance: HTMLParagraphElement) => void);
}>, import("@lifesg/react-design-system/typography").TypographyProps>, keyof import("@lifesg/react-design-system/typography").TypographyProps> & import("@lifesg/react-design-system/typography").TypographyProps, never>> & string;
export declare const MultiEntryAccordionItem: import("styled-components/dist/types").IStyledComponentBase<"web", import("styled-components/dist/types").Substitute<import("@lifesg/react-design-system/accordion").AccordionItemProps & import("react").RefAttributes<import("@lifesg/react-design-system/accordion").AccordionItemHandle>, MultiEntryAccordionItemProps>> & string & Omit<(props: import("@lifesg/react-design-system/accordion").AccordionItemProps & import("react").RefAttributes<import("@lifesg/react-design-system/accordion").AccordionItemHandle>) => import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>>, keyof import("react").Component<any, {}, any>>;
export declare const AddMultiEntryButton: import("styled-components/dist/types").IStyledComponentBase<"web", import("styled-components").FastOmit<import("@lifesg/react-design-system/button-with-icon").ButtonWithIconProps & import("react").RefAttributes<HTMLButtonElement>, never>> & string & Omit<(props: import("@lifesg/react-design-system/button-with-icon").ButtonWithIconProps & import("react").RefAttributes<HTMLButtonElement>) => import("react").ReactElement<any, string | import("react").JSXElementConstructor<any>>, keyof import("react").Component<any, {}, any>>;
export {};
